/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/

var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);

// main.ts
var main_exports = {};
__export(main_exports, {
  default: () => NoteDashboardPlugin
});
module.exports = __toCommonJS(main_exports);
var import_obsidian4 = require("obsidian");

// src/data.ts
var import_obsidian = require("obsidian");

// src/stats/word-count.ts
function countWords(content) {
  if (!content)
    return 0;
  let t = content.replace(/^---[\s\S]*?---\n*/, "").replace(/```[\s\S]*?```/g, "").replace(/`[^`\n]+`/g, "").replace(/!\[\[[^\]\n]*\]\]/g, "").replace(/\[\[([^\]|#\n^]+)(?:[#|][^\]]*)?\]\]/g, "$1").replace(/\[([^\]\n]*)\]\([^)\n]+\)/g, "$1").replace(/([\*_]{1,3})([^\*_]*?)\1/g, "$2").replace(/^#+\s*/gm, "").replace(/^[\s>*+-]\s*/gm, "").replace(/^\d+\.\s*/gm, "");
  const cjk = (t.match(/\p{Script=Han}/gu) || []).length;
  const other = t.replace(/\p{Script=Han}/gu, " ").split(/\s+/).filter((w) => w).length;
  return cjk + other;
}
function fmtNum(n) {
  if (n === 0)
    return "0";
  if (n >= 1e5)
    return (n / 1e3).toFixed(0) + "k";
  if (n >= 1e3)
    return (n / 1e3).toFixed(n % 1e3 === 0 ? 0 : 1).replace(/\.0$/, "") + "k";
  return "" + n;
}

// src/data.ts
var wordCountCache = /* @__PURE__ */ new Map();
async function collectData(vault, exclude, planPath, taskTags) {
  var _a;
  const allFiles = vault.getMarkdownFiles().filter((f) => {
    const parts = f.path.split("/");
    return !parts.some((p) => exclude.includes(p));
  });
  const dateWords = /* @__PURE__ */ new Map();
  const dateCount = /* @__PURE__ */ new Map();
  const folderMap = /* @__PURE__ */ new Map();
  let totalWords = 0;
  const fileWords = /* @__PURE__ */ new Map();
  const now = (0, import_obsidian.moment)();
  const todayStr = now.format("YYYY-MM-DD");
  let todayWords = 0;
  const uniqueDays = /* @__PURE__ */ new Set();
  const allTasks = [];
  const BATCH_SIZE = 50;
  const batches = [];
  for (let i = 0; i < allFiles.length; i += BATCH_SIZE) {
    batches.push(allFiles.slice(i, i + BATCH_SIZE));
  }
  for (const batch of batches) {
    const results = await Promise.all(batch.map(async (file) => {
      const cached = wordCountCache.get(file.path);
      if (cached && cached.mtime === file.stat.mtime) {
        return { file, content: "", words: cached.words };
      }
      const content = await vault.cachedRead(file);
      const words = countWords(content);
      return { file, content, words };
    }));
    for (const { file, content, words } of results) {
      totalWords += words;
      fileWords.set(file.path, words);
      wordCountCache.set(file.path, { mtime: file.stat.mtime, words });
      const fileDate = (0, import_obsidian.moment)(file.stat.mtime).format("YYYY-MM-DD");
      dateWords.set(fileDate, (dateWords.get(fileDate) || 0) + words);
      dateCount.set(fileDate, (dateCount.get(fileDate) || 0) + 1);
      uniqueDays.add(fileDate);
      if (fileDate === todayStr) {
        todayWords += words;
      }
      const folderPath = ((_a = file.parent) == null ? void 0 : _a.path) || "";
      if (!folderMap.has(folderPath)) {
        folderMap.set(folderPath, { words: 0, notes: 0 });
      }
      const fd = folderMap.get(folderPath);
      fd.words += words;
      fd.notes += 1;
      const lines = content.split("\n");
      lines.forEach((line, idx) => {
        const match = line.match(/^\s*[-*+] \[([ xX])\] (.+)/);
        if (match) {
          allTasks.push({
            path: file.path,
            line: idx + 1,
            text: match[2],
            completed: /[xX]/.test(match[1])
          });
        }
      });
    }
  }
  const folderData = [...folderMap.entries()].map(([path, data]) => ({
    name: path.split("/").pop() || "\u672A\u5206\u7C7B",
    path,
    words: data.words,
    notes: data.notes
  })).sort((a, b) => b.words - a.words);
  let streak = 0;
  const streakD = /* @__PURE__ */ new Date();
  streakD.setHours(0, 0, 0, 0);
  for (let i = 0; i < 365; i++) {
    const d = streakD.getFullYear() + "-" + String(streakD.getMonth() + 1).padStart(2, "0") + "-" + String(streakD.getDate()).padStart(2, "0");
    if (dateWords.has(d)) {
      streak++;
      streakD.setDate(streakD.getDate() - 1);
    } else if (i > 0) {
      break;
    } else {
      streakD.setDate(streakD.getDate() - 1);
    }
  }
  const nowM = /* @__PURE__ */ new Date();
  const monthStart = new Date(nowM.getFullYear(), nowM.getMonth(), 1);
  const daysInMonth = new Date(nowM.getFullYear(), nowM.getMonth() + 1, 0).getDate();
  let monthActive = 0;
  for (let i = 0; i < daysInMonth; i++) {
    const d = monthStart.getFullYear() + "-" + String(monthStart.getMonth() + 1).padStart(2, "0") + "-" + String(monthStart.getDate()).padStart(2, "0");
    if (dateWords.has(d))
      monthActive++;
    monthStart.setDate(monthStart.getDate() + 1);
  }
  let planContent = null;
  if (planPath) {
    try {
      const planFile = vault.getAbstractFileByPath(planPath);
      if (planFile instanceof import_obsidian.TFile) {
        planContent = await vault.cachedRead(planFile);
      }
    } catch (e) {
    }
  }
  const pendingTasks = allTasks.filter((t) => !t.completed);
  const totalDone = allTasks.filter((t) => t.completed).length;
  return {
    allFiles,
    totalWords,
    fileWords,
    dateWords,
    dateCount,
    todayWords,
    uniqueDays,
    streak,
    monthActive,
    daysInMonth,
    folderData,
    totalDone,
    totalTasks: allTasks.length,
    pendingTasks,
    allTasks,
    planContent
  };
}

// src/utils.ts
function isDarkMode() {
  return document.body.classList.contains("theme-dark");
}
function escapeHtml(str) {
  return str.replace(/&/g, "&amp;").replace(/</g, "&lt;").replace(/>/g, "&gt;").replace(/"/g, "&quot;").replace(/'/g, "&#39;");
}

// src/components/stats-cards.ts
function renderStatsCards(data, scheme) {
  const cG = isDarkMode() ? "#86efac" : "#166534";
  const cO = isDarkMode() ? "#fdba74" : "#9a3412";
  const mini = (icon, label, value, color, iconBg, shadowColor) => `<div class="nd-mini" style="--nd-card-shadow:${shadowColor};">
            <div class="nd-stat-icon">
                <span class="nd-mini-icon" style="background:radial-gradient(circle,${iconBg} 0%,transparent 70%);">${icon}</span>
            </div>
            <div class="nd-stat-label">${label}</div>
            <div class="nd-val" style="font-size:15px;font-weight:700;margin-top:2px;color:${color || "var(--text-normal)"};">${value}</div>
        </div>`;
  let s = '<div class="nd-grid nd-grid-stagger">';
  s += mini("\u{1F4DA}", "\u7B14\u8BB0\u603B\u6570", "" + data.allFiles.length, null, scheme.bar[0] + "25", scheme.bar[0] + "30");
  s += mini("\u{1F4C4}", "\u603B\u8BCD\u6570", fmtNum(data.totalWords), null, scheme.bar[1] + "25", scheme.bar[1] + "30");
  s += mini("\u{1F4C5}", "\u6D3B\u8DC3\u5929\u6570", "" + data.uniqueDays.size, null, scheme.bar[2] + "25", scheme.bar[2] + "30");
  s += mini("\u270D\uFE0F", "\u4ECA\u65E5\u5DF2\u5199", fmtNum(data.todayWords) + " \u8BCD", cG, "#22c55e25", "#22c55e30");
  s += mini("\u{1F525}", "\u5F53\u524D\u8FDE\u7EED", data.streak + " \u5929", cO, "#f9731625", "#f9731630");
  s += mini("\u{1F4C2}", "\u6587\u4EF6\u5939\u6570", "" + data.folderData.length, null, scheme.bar[3] + "25", scheme.bar[3] + "30");
  s += `<div class="nd-full nd-anim">
        <span style="font-size:20px;margin-right:8px;">\u{1F4C5}</span>
        <span style="font-size:11px;color:var(--text-muted);">\u672C\u6708\u6D3B\u8DC3</span>
        <span style="font-size:16px;font-weight:700;margin-left:8px;color:${cO};">${data.monthActive}/${data.daysInMonth} \u5929</span>
    </div>`;
  s += "</div>";
  return s;
}

// src/components/heatmap.ts
var DAYS = ["\u65E5", "\u4E00", "\u4E8C", "\u4E09", "\u56DB", "\u4E94", "\u516D"];
function renderHeatmap(data, scheme, heatWeeks, heatLevels) {
  const S = 13, G = 2, R = 2, PT = 20, MH = 18, MB = 4, LW = 22;
  const W = heatWeeks;
  const now = /* @__PURE__ */ new Date();
  const end = new Date(now.getFullYear(), now.getMonth(), now.getDate());
  const start = new Date(end.getTime() - ((W - 1) * 7 + (6 - end.getDay())) * 24 * 60 * 60 * 1e3);
  const level = (words) => {
    if (words >= heatLevels[2])
      return 4;
    if (words >= heatLevels[1])
      return 3;
    if (words >= heatLevels[0])
      return 2;
    if (words > 0)
      return 1;
    return 0;
  };
  const clr = (lv) => {
    if (lv === 0)
      return isDarkMode() ? "#161b22" : "#ebedf0";
    const colors = scheme.bar;
    return colors[Math.min(lv - 1, colors.length - 1)];
  };
  const mMap = /* @__PURE__ */ new Map();
  for (let c = 0; c < W; c++) {
    const d = new Date(start.getTime() + c * 7 * 24 * 60 * 60 * 1e3);
    if (d.getDate() <= 7) {
      mMap.set(c, d.getMonth() + 1 + "\u6708");
    }
  }
  const cellDelay = (c) => `${c * 15}ms`;
  let hm = '<div class="nd-card" style="overflow:clip;"><div style="display:flex;gap:2px;">';
  hm += `<div style="flex:0 0 ${LW}px;padding:${PT + MH + MB}px 0 0;">`;
  for (let r = 0; r < 7; r++) {
    hm += `<div style="height:${S}px;margin-bottom:${G}px;font-size:9px;color:var(--text-muted);text-align:center;line-height:${S}px;">${DAYS[r]}</div>`;
  }
  hm += "</div>";
  hm += `<div class="nd-hide nd-heat-scroll" style="overflow-x:auto;flex:1;min-width:0;padding:${PT}px 12px 0 0;"><div style="min-width:max-content;">`;
  hm += `<div style="position:relative;height:${MH}px;margin-bottom:${MB}px;">`;
  for (const [col, label] of mMap) {
    const left = col * (S + G);
    hm += `<span style="position:absolute;left:${left}px;top:0;font-size:9px;color:var(--text-muted);white-space:nowrap;line-height:${MH}px;pointer-events:none;">${label}</span>`;
  }
  hm += "</div>";
  for (let r = 0; r < 7; r++) {
    hm += `<div style="display:flex;gap:${G}px;margin-bottom:${G}px;">`;
    for (let c = 0; c < W; c++) {
      const d = new Date(start.getTime() + (c * 7 + r) * 24 * 60 * 60 * 1e3);
      const k = d.getFullYear() + "-" + String(d.getMonth() + 1).padStart(2, "0") + "-" + String(d.getDate()).padStart(2, "0");
      const words = data.dateWords.get(k) || 0;
      const cnt = data.dateCount.get(k) || 0;
      const lv = level(words);
      const tip = cnt ? `${d.getMonth() + 1}\u6708${d.getDate()}\u65E5 \xB7 ${cnt}\u7BC7 \xB7 ${fmtNum(words)}\u8BCD` : `${d.getMonth() + 1}\u6708${d.getDate()}\u65E5`;
      hm += `<div class="nd-heat-col" style="width:${S}px;height:${S}px;border-radius:${R}px;flex-shrink:0;background:${clr(lv)};transition:background .15s;animation-delay:${cellDelay(c)}" title="${tip}" data-l="${lv}"></div>`;
    }
    hm += "</div>";
  }
  hm += "</div></div></div>";
  hm += '<div style="display:flex;align-items:center;justify-content:flex-end;gap:4px;padding:8px 12px 10px;font-size:10px;color:var(--text-muted);">';
  hm += '<span style="margin-right:2px;">Less</span>';
  for (let i = 0; i <= 4; i++) {
    hm += `<div style="width:11px;height:11px;border-radius:${R}px;background:${clr(i)};" data-l="${i}"></div>`;
  }
  hm += '<span style="margin-left:2px;">More</span></div></div>';
  return hm;
}

// src/components/chart.ts
var import_obsidian2 = require("obsidian");
function renderChart(data, scheme, monthCount, dayCount) {
  const now = (0, import_obsidian2.moment)();
  const monthRows = [];
  for (let i = monthCount - 1; i >= 0; i--) {
    const m = (0, import_obsidian2.moment)().subtract(i, "months");
    let words = 0;
    const daysInMonth = m.daysInMonth();
    for (let d = 1; d <= daysInMonth; d++) {
      const dayStr = m.clone().date(d).format("YYYY-MM-DD");
      words += data.dateWords.get(dayStr) || 0;
    }
    monthRows.push({
      label: m.format("M\u6708"),
      words,
      isCurrent: i === 0
    });
  }
  const dayRows = [];
  for (let i = dayCount - 1; i >= 0; i--) {
    const d = (0, import_obsidian2.moment)().subtract(i, "days");
    const key = d.format("YYYY-MM-DD");
    dayRows.push({
      label: d.format("M/D"),
      words: data.dateWords.get(key) || 0,
      isCurrent: i === 0
    });
  }
  const dayPaneId = "nd-day-" + Date.now();
  const monthPaneId = "nd-month-" + Date.now();
  const toggleId = "nd-toggle-" + Date.now();
  let html = '<div class="nd-card nd-pad nd-anim nd-anim-2">';
  html += '<div style="display:flex;align-items:center;justify-content:space-between;margin-bottom:8px;">';
  html += '<span style="font-size:14px;font-weight:600;">\u{1F4CA} \u6708\u5EA6/7\u5929\u56FE\u8868</span>';
  html += `<div id="${toggleId}" class="nd-chart-toggle" style="position:relative;display:flex;align-items:center;background:var(--background-secondary);border-radius:20px;padding:2px;cursor:pointer;border:1px solid var(--background-modifier-border);font-size:11px;font-weight:500;overflow:hidden;flex-shrink:0;user-select:none;height:26px;min-width:120px;box-sizing:border-box;">`;
  html += `<div style="position:absolute;top:2px;left:2px;width:calc(50% - 2px);height:calc(100% - 4px);border-radius:16px;background:var(--interactive-accent);transition:left .3s cubic-bezier(.4,0,.2,1);z-index:1;box-shadow:0 1px 3px rgba(0,0,0,.15);" data-ind></div>`;
  html += `<span data-view="day" class="nd-chart-tab" style="position:relative;z-index:2;display:flex;align-items:center;justify-content:center;flex:1;height:100%;color:#fff;white-space:nowrap;transition:color .25s ease;padding:0 10px;">\u8FD17\u5929</span>`;
  html += `<span data-view="month" class="nd-chart-tab" style="position:relative;z-index:2;display:flex;align-items:center;justify-content:center;flex:1;height:100%;color:var(--text-muted);white-space:nowrap;transition:color .25s ease;padding:0 10px;">\u6708\u5EA6</span>`;
  html += `</div></div>`;
  html += `<div id="${dayPaneId}" class="nd-chart-pane" data-chart-type="day" data-chart-data='${JSON.stringify(dayRows)}' data-bar0="${scheme.bar[0]}" data-bar1="${scheme.bar[1]}" data-primary="${scheme.primary}"></div>`;
  html += `<div id="${monthPaneId}" class="nd-chart-pane" data-chart-type="month" data-chart-data='${JSON.stringify(monthRows)}' data-bar0="${scheme.bar[0]}" data-bar1="${scheme.bar[1]}" data-primary="${scheme.primary}" style="display:none;"></div>`;
  html += "</div>";
  return html;
}
function renderChartPane(el, data, bar0, bar1, primary) {
  const maxW = Math.max(...data.map((r) => r.words), 1);
  const h = 120;
  const niceStep = Math.pow(10, Math.floor(Math.log10(maxW / 4)));
  const cs = [niceStep, niceStep * 2, niceStep * 5, niceStep * 10];
  let step = cs[0];
  for (let i = 0; i < cs.length; i++) {
    if (cs[i] * 4 >= maxW) {
      step = cs[i];
      break;
    }
  }
  const yMax = step * 4;
  let s = '<div style="display:flex;align-items:stretch;">';
  s += '<div style="flex-shrink:0;min-width:22px;display:flex;flex-direction:column;justify-content:space-between;padding:0 5px 4px 0;height:' + h + 'px;">';
  for (let t = 4; t >= 0; t--) {
    s += '<div style="font-size:9px;color:var(--text-faint);text-align:right;line-height:1;">' + (t * step).toLocaleString() + "</div>";
  }
  s += '</div><div style="flex:1;min-width:0;"><div style="display:flex;align-items:flex-end;gap:2px;height:' + h + 'px;">';
  data.forEach((r) => {
    const pct = yMax > 0 ? Math.max(1, r.words / yMax * 100) : 1;
    const c = r.isCurrent ? bar0 : bar1;
    s += '<div style="display:flex;flex-direction:column;align-items:center;justify-content:flex-end;flex:1 1 0;height:100%;">';
    s += '<div class="nd-chart-bar" data-h="' + pct + '" style="width:75%;max-width:36px;height:0%;border-radius:5px 5px 2px 2px;background:' + c + ';cursor:pointer;transition:height 1.2s cubic-bezier(.25,.46,.45,.94);position:relative;">';
    s += '<div class="nd-chart-bar-num" style="position:absolute;bottom:100%;left:0;right:0;display:flex;justify-content:center;pointer-events:none;margin-bottom:2px;opacity:0;transition:opacity .6s ease .8s;"><span style="font-size:8px;font-weight:700;white-space:nowrap;color:var(--text-muted);">' + r.words.toLocaleString() + "</span></div>";
    s += '</div><span style="font-size:9px;color:' + (r.isCurrent ? primary : "var(--text-muted)") + ";margin-top:3px;white-space:nowrap;line-height:1;font-weight:" + (r.isCurrent ? 700 : 400) + ';">' + r.label + "</span></div>";
  });
  s += "</div></div></div>";
  s += '<div style="display:flex;align-items:center;justify-content:center;gap:14px;margin-top:6px;font-size:10px;color:var(--text-muted);">';
  s += '<span style="display:flex;align-items:center;gap:4px;"><span style="width:10px;height:10px;border-radius:3px;background:' + bar0 + ';display:inline-block;"></span> \u5F53\u524D</span>';
  s += '<span style="display:flex;align-items:center;gap:4px;"><span style="width:10px;height:10px;border-radius:3px;background:' + bar1 + ';display:inline-block;"></span> \u5176\u4ED6</span></div>';
  el.innerHTML = s;
  requestAnimationFrame(() => {
    requestAnimationFrame(() => {
      el.querySelectorAll(".nd-chart-bar").forEach((b) => {
        b.style.height = b.dataset.h + "%";
      });
      el.querySelectorAll(".nd-chart-bar-num").forEach((n) => {
        n.style.opacity = "1";
      });
    });
  });
}
function animChartBars(el) {
  el.querySelectorAll(".nd-chart-bar").forEach((b) => {
    b.style.transition = "none";
    b.style.height = "0%";
  });
  el.querySelectorAll(".nd-chart-bar-num").forEach((n) => {
    n.style.opacity = "0";
  });
  requestAnimationFrame(() => {
    requestAnimationFrame(() => {
      el.querySelectorAll(".nd-chart-bar").forEach((b) => {
        b.style.transition = "height 1.2s cubic-bezier(.25,.46,.45,.94)";
        b.style.height = b.dataset.h + "%";
      });
      el.querySelectorAll(".nd-chart-bar-num").forEach((n) => {
        n.style.opacity = "1";
      });
    });
  });
}

// src/components/ranking.ts
var RANK = ["\u{1F947}", "\u{1F948}", "\u{1F949}"];
function renderRankItem(d, i, opts, scheme, totalWords) {
  const top = i < 3;
  const rankStr = opts.showEmojiRank !== false ? RANK[i] || "" + (i + 1) : "" + (i + 1);
  const color = scheme.bar[i % scheme.bar.length];
  const share = totalWords > 0 ? d.words / totalWords * 100 : 0;
  const shareStr = share >= 1 ? share.toFixed(1) + "%" : share > 0 ? "<1%" : "0%";
  const barW = Math.max(2, Math.round(share));
  const icon = opts.icon || "\u{1F4C1}";
  const nameSpan = opts.link ? `<span style="flex:1;font-size:11px;overflow:hidden;text-overflow:ellipsis;white-space:nowrap;font-weight:${top ? 600 : 400};cursor:pointer;" data-nd-link="${escapeHtml(opts.link)}">${icon} ${escapeHtml(d.name)}</span>` : `<span style="flex:1;font-size:11px;overflow:hidden;text-overflow:ellipsis;white-space:nowrap;font-weight:${top ? 600 : 400};">${icon} ${escapeHtml(d.name)}</span>`;
  let h = `<div class="nd-row" style="display:flex;align-items:center;gap:4px;padding:3px 6px;${top ? "background:var(--background-primary-alt);border-radius:6px;" : ""}">`;
  h += `<span style="width:18px;text-align:center;font-size:${top ? 12 : 10}px;font-weight:${top ? 600 : 400};color:${top ? "var(--text-normal)" : "var(--text-muted)"};flex-shrink:0;">${rankStr}</span>`;
  h += nameSpan;
  h += `<div style="display:flex;align-items:center;gap:2px;flex-shrink:0;">`;
  h += `<span style="font-size:8px;color:var(--text-faint);min-width:20px;text-align:right;">${shareStr}</span>`;
  h += `<div class="nd-bar" style="width:50px;">`;
  h += `<div class="nd-bar-fill" data-w="${barW}" style="width:${barW}%;height:100%;background:linear-gradient(90deg,${color}bb,${color});border-radius:6px;min-width:3px;"></div>`;
  h += "</div></div>";
  if (opts.showNotes)
    h += `<span style="width:30px;text-align:right;font-size:10px;color:var(--text-muted);flex-shrink:0;">${d.notes || 0}</span>`;
  h += `<span style="width:45px;text-align:right;font-size:10px;font-weight:600;flex-shrink:0;">${fmtNum(d.words)}</span></div>`;
  return h;
}
function rankHeader(cols) {
  let h = '<div style="display:flex;align-items:center;gap:4px;padding:4px 6px;font-size:9px;color:var(--text-muted);font-weight:600;background:var(--background-secondary);border-radius:6px;margin-bottom:3px;">';
  h += '<span style="width:18px;flex-shrink:0;text-align:center;">#</span>';
  cols.forEach((c) => h += `<span style="${c.style || "flex:1"}">${c.label}</span>`);
  return h + "</div>";
}
function renderRanking(data, scheme, folderTopN) {
  const fileRankData = data.allFiles.map((f) => {
    var _a;
    return {
      name: f.name.replace(".md", ""),
      path: f.path,
      words: ((_a = data.fileWords) == null ? void 0 : _a.get(f.path)) || 0,
      notes: 1
    };
  }).sort((a, b) => b.words - a.words);
  let html = '<div class="nd-card nd-pad nd-anim nd-anim-2" style="margin-bottom:10px;">';
  const folderToggleId = "nd-folder-toggle-" + Date.now();
  const folderListId = "nd-folder-list-" + Date.now();
  const fileListId = "nd-file-list-" + Date.now();
  html += `<div style="display:flex;align-items:center;gap:8px;margin-bottom:8px;">`;
  html += `<span style="font-size:14px;font-weight:600;">\u{1F4C2} \u6392\u884C\u699C</span>`;
  html += `<div style="display:flex;gap:4px;margin-left:auto;">`;
  html += `<button class="nd-rank-tab nd-rank-tab-active" data-target="${folderListId}" data-other="${fileListId}" style="font-size:10px;padding:2px 8px;border-radius:4px;border:1px solid var(--interactive-accent);background:var(--interactive-accent);color:#fff;cursor:pointer;">\u6587\u4EF6\u5939</button>`;
  html += `<button class="nd-rank-tab" data-target="${fileListId}" data-other="${folderListId}" style="font-size:10px;padding:2px 8px;border-radius:4px;border:1px solid var(--background-modifier-border);background:transparent;color:var(--text-muted);cursor:pointer;">\u6587\u4EF6</button>`;
  html += `</div></div>`;
  html += `<div id="${folderListId}">`;
  let listHTML = '<div style="display:flex;flex-direction:column;gap:1px;">';
  listHTML += rankHeader([
    { label: "\u6587\u4EF6\u5939", style: "flex:1" },
    { label: "\u5360\u6BD4", style: "width:72px;text-align:center;flex-shrink:0" },
    { label: "\u7B14\u8BB0", style: "width:30px;text-align:right;flex-shrink:0" },
    { label: "\u8BCD\u6570", style: "width:45px;text-align:right;flex-shrink:0" }
  ]);
  const topFolders = data.folderData.slice(0, folderTopN);
  for (let i = 0; i < topFolders.length; i++) {
    listHTML += renderRankItem(topFolders[i], i, { showEmojiRank: true, showNotes: true }, scheme, data.totalWords);
  }
  listHTML += "</div>";
  html += listHTML;
  html += `</div>`;
  html += `<div id="${fileListId}" style="display:none;">`;
  let fileHTML = '<div style="display:flex;flex-direction:column;gap:1px;">';
  fileHTML += rankHeader([
    { label: "\u6587\u4EF6", style: "flex:1" },
    { label: "\u5360\u6BD4", style: "width:72px;text-align:center;flex-shrink:0" },
    { label: "\u8BCD\u6570", style: "width:45px;text-align:right;flex-shrink:0" }
  ]);
  const topFiles = fileRankData.slice(0, folderTopN);
  for (let i = 0; i < topFiles.length; i++) {
    fileHTML += renderRankItem(topFiles[i], i, { icon: "\u{1F4C4}", link: topFiles[i].path }, scheme, data.totalWords);
  }
  fileHTML += "</div>";
  html += fileHTML;
  html += `</div>`;
  html += "</div>";
  return html;
}

// src/components/plan-progress.ts
function renderPlanProgress(planContent) {
  if (!planContent)
    return null;
  const tasks = planContent.match(/^\s*[-*+] \[([ xX])\] .+/gm) || [];
  const total = tasks.length;
  const done = tasks.filter((t) => /\[[xX]\]/.test(t)).length;
  const pct = total > 0 ? Math.round(done / total * 100) : 0;
  let s = '<div data-section="plan"><div class="nd-card nd-pad nd-anim nd-anim-3">';
  s += `<div style="display:flex;align-items:center;gap:8px;margin-bottom:8px;">`;
  s += `<span style="font-size:15px;font-weight:600;">\u{1F331} \u6210\u957F\u8FDB\u5EA6</span>`;
  s += `<span style="font-size:12px;color:var(--text-muted);">${done}/${total} \xB7 ${pct}%</span></div>`;
  s += `<div class="nd-shimmer" style="width:100%;height:20px;background:var(--background-secondary);border-radius:10px;overflow:hidden;border:1px solid var(--background-modifier-border);box-shadow:inset 0 1px 2px rgba(0,0,0,0.05);">`;
  s += `<div class="nd-bar-fill" data-w="${Math.max(pct, 2)}" style="width:${Math.max(pct, 2)}%;height:100%;background:linear-gradient(90deg,#86efac,#22c55e,#16a34a);border-radius:10px;display:flex;align-items:center;justify-content:center;">`;
  if (pct > 10) {
    s += `<span style="font-size:11px;font-weight:600;color:#fff;text-shadow:0 1px 2px rgba(0,0,0,0.2);">${pct}%</span>`;
  }
  s += "</div></div></div></div>";
  return s;
}

// src/components/recent-edits.ts
function getTimeDiff(mtime) {
  const now = Date.now();
  const diff = now - mtime;
  if (diff < 0)
    return "\u521A\u521A";
  const mins = Math.floor(diff / 6e4);
  if (mins < 1)
    return "\u521A\u521A";
  if (mins < 60)
    return `${mins}\u5206\u949F\u524D`;
  const hours = Math.floor(mins / 60);
  if (hours < 24)
    return `${hours}\u5C0F\u65F6\u524D`;
  const days = Math.floor(hours / 24);
  if (days < 7)
    return `${days}\u5929\u524D`;
  const d = new Date(mtime);
  return `${d.getMonth() + 1}/${d.getDate()}`;
}
function renderRecentEdits(data) {
  const recentEdits = [...data.allFiles].sort((a, b) => (b.stat.mtime || 0) - (a.stat.mtime || 0)).slice(0, 5);
  if (recentEdits.length === 0)
    return "";
  let r = '<div data-section="recent"><div class="nd-card nd-pad nd-anim" style="margin-bottom:10px;">';
  r += '<div style="display:flex;align-items:center;gap:6px;margin-bottom:10px;">';
  r += '<span style="font-size:15px;font-weight:600;">\u270F\uFE0F \u6700\u8FD1\u7F16\u8F91</span>';
  r += `<span style="font-size:11px;color:var(--text-muted);">\u5171${recentEdits.length}\u4E2A</span></div>`;
  r += '<div style="display:flex;flex-direction:column;gap:4px;">';
  const renderRecentItem = (file) => {
    const name = file.name.replace(".md", "");
    const timeDiff = file.stat.mtime ? getTimeDiff(file.stat.mtime) : "";
    return `<div class="nd-row" style="display:flex;align-items:center;gap:8px;padding:6px 8px;cursor:pointer;" data-nd-link="${escapeHtml(file.path)}"><span style="flex:1;font-size:12px;color:var(--text-normal);overflow:hidden;text-overflow:ellipsis;white-space:nowrap;">\u{1F4C4} ${escapeHtml(name)}</span><span style="font-size:10px;color:var(--text-faint);white-space:nowrap;">${timeDiff}</span></div>`;
  };
  r += renderRecentItem(recentEdits[0]);
  if (recentEdits.length > 1) {
    for (let i = 1; i < recentEdits.length; i++) {
      r += renderRecentItem(recentEdits[i]);
    }
  }
  r += "</div></div></div>";
  return r;
}

// src/components/tasks-board.ts
function analyzeTask(task, taskTags) {
  const text = task.text || "";
  const isUrgent = /!!/.test(text);
  const isImportant = /!(?!!)/.test(text) && !/!!/.test(text) || /#important/i.test(text);
  const dueMatch = text.match(/📅\s*(\d{4}-\d{2}-\d{2})/);
  const dueDate = dueMatch ? new Date(dueMatch[1]) : null;
  let dueStatus = "none";
  if (dueDate) {
    const diff = Math.ceil((dueDate.getTime() - Date.now()) / (1e3 * 60 * 60 * 24));
    if (diff < 0)
      dueStatus = "overdue";
    else if (diff === 0)
      dueStatus = "today";
    else if (diff <= 2)
      dueStatus = "soon";
    else
      dueStatus = "future";
  }
  const tagPattern = new RegExp(taskTags.map((t) => t.replace(/[.*+?^${}()|[\]\\]/g, "\\$&") + "(?!\\w)").join("|"), "gi");
  const displayText = text.replace(/!!/g, "").replace(/!(?!!)/g, "").replace(tagPattern, "").replace(/📅\s*\d{4}-\d{2}-\d{2}/g, "").replace(/\s{2,}/g, " ").trim();
  return { text, displayText, isUrgent, isImportant, dueDate, dueStatus };
}
function badge(text, color, bg, pulse) {
  const a = pulse ? "animation:ndPulseTag 2s ease-in-out infinite;" : "";
  return `<span style="display:inline-flex;font-size:9px;padding:0 6px;border-radius:6px;background:${bg};color:${color};font-weight:600;line-height:1.8;${a}">${text}</span>`;
}
function dueBadge(a) {
  if (!a.dueDate)
    return "";
  const m = {
    overdue: { l: "\u903E\u671F", c: "#ef4444", b: "rgba(239,68,68,0.15)" },
    today: { l: "\u4ECA\u65E5\u5230\u671F", c: "#f97316", b: "rgba(249,115,22,0.15)" },
    soon: { l: "\u5373\u5C06\u5230\u671F", c: "#ca8a04", b: "rgba(234,179,8,0.12)" },
    future: { l: `${a.dueDate.getMonth() + 1}/${a.dueDate.getDate()}`, c: "var(--text-faint)", b: "transparent" }
  };
  const info = m[a.dueStatus];
  return info ? badge(`\u{1F4C5} ${info.l}`, info.c, info.b, a.dueStatus === "overdue" || a.dueStatus === "today") : "";
}
function priBadge(a) {
  if (a.isUrgent)
    return badge("\u{1F534} \u7D27\u6025", "#ef4444", "rgba(239,68,68,0.15)", true);
  if (a.isImportant)
    return badge("\u{1F7E0} \u91CD\u8981", "#f97316", "rgba(249,115,22,0.12)", false);
  return "";
}
function renderTaskRow(task, taskTags) {
  const a = analyzeTask(task, taskTags);
  const acc = a.isUrgent ? "#ef4444" : a.isImportant ? "#f97316" : "var(--text-muted)";
  const taskId = "nd-t-" + task.path.replace(/[^a-z0-9]/gi, "-") + "-L" + task.line;
  return `<div class="nd-tr" style="display:flex;align-items:center;gap:6px;padding:3px 8px 3px 12px;border-radius:6px;border-left:2px solid ${acc}33;transition:background .15s;"><span id="${taskId}" class="nd-cb" data-path="${escapeHtml(task.path)}" data-line="${task.line}" style="color:var(--text-faint);font-size:12px;flex-shrink:0;cursor:pointer;transition:transform .15s,color .15s;user-select:none;" title="\u70B9\u51FB\u6807\u8BB0\u5B8C\u6210">\u2B1C</span><span style="flex:1;font-size:12.5px;color:var(--text-normal);line-height:1.5;word-break:break-word;min-width:0;">${escapeHtml(a.displayText || a.text)}</span><span style="display:flex;align-items:center;gap:3px;flex-shrink:0;">${priBadge(a)}${dueBadge(a)}</span></div>`;
}
function renderTasksBoard(data, scheme, taskTags, maxOpen, app) {
  const { pendingTasks, totalDone, allTasks } = data;
  const totalAll = totalDone + pendingTasks.length;
  const donePct = totalAll > 0 ? Math.round(totalDone / totalAll * 100) : 0;
  const analyzedCache = /* @__PURE__ */ new Map();
  for (const t of pendingTasks) {
    analyzedCache.set(t, analyzeTask(t, taskTags));
  }
  let urgCnt = 0, impCnt = 0;
  for (const a of analyzedCache.values()) {
    if (a.isUrgent)
      urgCnt++;
    else if (a.isImportant)
      impCnt++;
  }
  const fileGroups = /* @__PURE__ */ new Map();
  for (const task of pendingTasks) {
    const f = task.path;
    if (!fileGroups.has(f))
      fileGroups.set(f, { file: f, tasks: [], done: 0, total: 0 });
    fileGroups.get(f).tasks.push(task);
  }
  for (const f of allTasks) {
    const g = fileGroups.get(f.path);
    if (g) {
      if (f.completed)
        g.done++;
      g.total++;
    }
  }
  const sortedFiles = [...fileGroups.values()].sort((a, b) => b.tasks.length - a.tasks.length);
  let k = `<div class="nd-card nd-anim nd-anim-4" style="padding:12px 14px;margin-bottom:10px;">`;
  k += `<div style="display:flex;align-items:center;justify-content:space-between;flex-wrap:wrap;gap:6px;margin-bottom:8px;">`;
  k += `<div style="display:flex;align-items:center;gap:8px;">`;
  k += `<span style="font-size:16px;font-weight:700;background:${scheme.gradient};-webkit-background-clip:text;-webkit-text-fill-color:transparent;">\u{1F4CB} \u5F85\u529E\u770B\u677F</span>`;
  k += `<span style="font-size:11px;color:var(--text-muted);font-weight:400;background:var(--background-secondary);padding:1px 8px;border-radius:8px;">${pendingTasks.length}\u9879</span>`;
  if (urgCnt > 0)
    k += `<span style="font-size:10px;padding:1px 7px;border-radius:6px;background:rgba(239,68,68,0.12);color:#ef4444;font-weight:600;">\u{1F534}${urgCnt}</span>`;
  if (impCnt > 0)
    k += `<span style="font-size:10px;padding:1px 7px;border-radius:6px;background:rgba(249,115,22,0.1);color:#f97316;font-weight:600;">\u{1F7E0}${impCnt}</span>`;
  k += `</div>`;
  k += `<div style="display:flex;align-items:center;gap:6px;">`;
  k += `<span style="font-size:10px;color:var(--text-muted);">${donePct}%</span>`;
  k += `<div style="width:64px;height:5px;border-radius:3px;background:var(--background-secondary);overflow:hidden;">`;
  k += `<div class="nd-bar-fill" style="width:${Math.max(donePct, 2)}%;height:100%;background:linear-gradient(90deg,#22c55e,#16a34a);border-radius:3px;"></div></div>`;
  k += `<span style="font-size:9px;color:var(--text-faint);">${totalDone}/${totalAll}</span>`;
  k += `</div></div>`;
  if (sortedFiles.length === 0) {
    k += `<div style="padding:20px;text-align:center;color:var(--text-muted);font-size:13px;">\u{1F389} \u6240\u6709\u4EFB\u52A1\u5DF2\u5B8C\u6210\uFF01</div>`;
  } else {
    sortedFiles.forEach((g, fi) => {
      var _a;
      const fn = ((_a = g.file.split("/").pop()) == null ? void 0 : _a.replace(".md", "")) || g.file;
      const pct = g.total > 0 ? Math.round(g.done / g.total * 100) : 0;
      const analyzed = g.tasks.map((t) => ({ task: t, ...analyzedCache.get(t) || analyzeTask(t, taskTags) }));
      const hasU = analyzed.some((a) => a.isUrgent);
      const hasI = analyzed.some((a) => a.isImportant && !a.isUrgent);
      analyzed.sort((a, b) => {
        if (a.isUrgent !== b.isUrgent)
          return a.isUrgent ? -1 : 1;
        if (a.isImportant !== b.isImportant)
          return a.isImportant ? -1 : 1;
        return 0;
      });
      const sorted = analyzed.map((a) => a.task);
      const cId = "nd-fc-" + fi;
      const defOpen = fi < maxOpen;
      k += `<div style="margin-bottom:4px;border-radius:10px;border:1px solid var(--background-modifier-border);overflow:hidden;transition:border-color .25s;">`;
      k += `<div class="nd-fh" data-target="${cId}" data-open="${defOpen ? "1" : "0"}" style="display:flex;align-items:center;gap:8px;padding:8px 12px;cursor:pointer;background:var(--background-primary);border-bottom:1px solid ${defOpen ? "var(--background-modifier-border)" : "transparent"};user-select:none;" title="${escapeHtml(g.file)}">`;
      k += `<span id="${cId}-a" style="flex-shrink:0;font-size:10px;color:var(--text-faint);transition:transform .3s;${defOpen ? "transform:rotate(90deg);" : ""}">\u25B6</span>`;
      k += `<span style="flex:1;font-size:12.5px;font-weight:600;color:var(--text-normal);overflow:hidden;text-overflow:ellipsis;white-space:nowrap;">\u{1F4C4} ${escapeHtml(fn)}</span>`;
      if (hasU)
        k += `<span style="font-size:8px;padding:0 5px;border-radius:4px;background:rgba(239,68,68,0.12);color:#ef4444;font-weight:700;line-height:1.8;">!!</span>`;
      else if (hasI)
        k += `<span style="font-size:8px;padding:0 5px;border-radius:4px;background:rgba(249,115,22,0.1);color:#f97316;font-weight:600;line-height:1.8;">!</span>`;
      k += `<div style="width:56px;height:6px;border-radius:3px;background:var(--background-secondary);overflow:hidden;flex-shrink:0;"><div style="width:${pct}%;height:100%;background:${scheme.gradient};border-radius:3px;transition:width .8s;"></div></div>`;
      k += `<span style="font-size:10px;color:var(--text-muted);white-space:nowrap;flex-shrink:0;min-width:28px;text-align:right;">${g.done}/${g.total}</span>`;
      k += `<span style="font-size:10px;color:var(--text-faint);white-space:nowrap;">${g.tasks.length}\u9879</span>`;
      k += `</div>`;
      k += `<div id="${cId}" data-open="${defOpen ? "1" : "0"}" class="nd-file-content${defOpen ? " nd-show" : ""}">`;
      sorted.forEach((t) => {
        k += renderTaskRow(t, taskTags);
      });
      k += `</div></div>`;
    });
  }
  k += "</div>";
  return k;
}

// src/color-schemes.ts
var COLOR_SCHEMES = {
  indigo: {
    primary: "#6366f1",
    accent: "#8b5cf6",
    gradient: "linear-gradient(135deg,#6366f1,#8b5cf6)",
    tag: "#6366f1",
    bar: ["#6366f1", "#8b5cf6", "#a78bfa", "#c4b5fd", "#a5b4fc", "#818cf8", "#6d28d9", "#4f46e5"]
  },
  emerald: {
    primary: "#10b981",
    accent: "#34d399",
    gradient: "linear-gradient(135deg,#10b981,#34d399)",
    tag: "#10b981",
    bar: ["#10b981", "#34d399", "#6ee7b7", "#a7f3d0", "#059669", "#047857", "#065f46", "#064e3b"]
  },
  amber: {
    primary: "#f59e0b",
    accent: "#fbbf24",
    gradient: "linear-gradient(135deg,#f59e0b,#fbbf24)",
    tag: "#f59e0b",
    bar: ["#f59e0b", "#fbbf24", "#fcd34d", "#fde68a", "#d97706", "#b45309", "#92400e", "#78350f"]
  },
  rose: {
    primary: "#f43f5e",
    accent: "#fb7185",
    gradient: "linear-gradient(135deg,#f43f5e,#fb7185)",
    tag: "#f43f5e",
    bar: ["#f43f5e", "#fb7185", "#fda4af", "#fecdd3", "#e11d48", "#be123c", "#9f1239", "#881337"]
  },
  sky: {
    primary: "#0ea5e9",
    accent: "#38bdf8",
    gradient: "linear-gradient(135deg,#0ea5e9,#38bdf8)",
    tag: "#0ea5e9",
    bar: ["#0ea5e9", "#38bdf8", "#7dd3fc", "#bae6fd", "#0284c7", "#0369a1", "#075985", "#0c4a6e"]
  },
  coral: {
    primary: "#f97316",
    accent: "#fb923c",
    gradient: "linear-gradient(135deg,#f97316,#fb923c)",
    tag: "#f97316",
    bar: ["#f97316", "#fb923c", "#fdba74", "#fed7aa", "#ea580c", "#c2410c", "#9a3412", "#7c2d12"]
  },
  slate: {
    primary: "#64748b",
    accent: "#94a3b8",
    gradient: "linear-gradient(135deg,#64748b,#94a3b8)",
    tag: "#64748b",
    bar: ["#64748b", "#94a3b8", "#cbd5e1", "#e2e8f0", "#475569", "#334155", "#1e293b", "#0f172a"]
  }
};

// src/settings.ts
var DEFAULT_SETTINGS = {
  exclude: ["\u9644\u4EF6", "\u6A21\u677F", "copilot"],
  planPath: "planning/\u6210\u957F\u8BA1\u5212.md",
  heatLevels: [400, 1200, 2500],
  heatWeeks: 54,
  monthCount: 12,
  dayCount: 7,
  folderTopN: 5,
  maxOpen: 3,
  taskTags: ["#urgent", "#important", "#doing", "#wip", "#\u8FDB\u884C\u4E2D", "#review", "#\u5F85\u56DE\u987E"],
  dueEmoji: "\u{1F4C5}",
  estThreshold: 200,
  estCoeff: 4,
  colorScheme: "indigo",
  sectionOrder: ["heat", "stats", "chart", "rank", "plan", "recent", "tasks"]
};

// src/setting-tab.ts
var import_obsidian3 = require("obsidian");
var NoteDashboardSettingTab = class extends import_obsidian3.PluginSettingTab {
  constructor(app, plugin) {
    super(app, plugin);
    this.plugin = plugin;
  }
  display() {
    const { containerEl } = this;
    containerEl.empty();
    containerEl.createEl("h2", { text: "\u7B14\u8BB0\u770B\u677F\u8BBE\u7F6E" });
    new import_obsidian3.Setting(containerEl).setName("\u914D\u8272\u65B9\u6848").setDesc("\u9009\u62E9\u770B\u677F\u7684\u914D\u8272\u4E3B\u9898").addDropdown((dropdown) => {
      Object.keys(COLOR_SCHEMES).forEach((scheme) => {
        dropdown.addOption(scheme, scheme);
      });
      dropdown.setValue(this.plugin.settings.colorScheme);
      dropdown.onChange(async (value) => {
        this.plugin.settings.colorScheme = value;
        await this.plugin.saveSettings();
      });
    });
    new import_obsidian3.Setting(containerEl).setName("\u6392\u9664\u6587\u4EF6\u5939").setDesc("\u8FD9\u4E9B\u6587\u4EF6\u5939\u4E0B\u7684\u7B14\u8BB0\u4E0D\u8BA1\u5165\u7EDF\u8BA1\uFF08\u7528\u9017\u53F7\u5206\u9694\uFF09").addText((text) => text.setPlaceholder("\u9644\u4EF6, \u6A21\u677F, copilot").setValue(this.plugin.settings.exclude.join(", ")).onChange(async (value) => {
      this.plugin.settings.exclude = value.split(",").map((s) => s.trim()).filter((s) => s);
      await this.plugin.saveSettings();
    }));
    new import_obsidian3.Setting(containerEl).setName("\u6210\u957F\u8BA1\u5212\u8DEF\u5F84").setDesc("\u76F8\u5BF9\u8DEF\u5F84\uFF0C\u7559\u7A7A\u9690\u85CF\u8FDB\u5EA6\u6761").addText((text) => text.setPlaceholder("planning/\u6210\u957F\u8BA1\u5212.md").setValue(this.plugin.settings.planPath).onChange(async (value) => {
      this.plugin.settings.planPath = value;
      await this.plugin.saveSettings();
    }));
    new import_obsidian3.Setting(containerEl).setName("\u70ED\u529B\u56FE\u5468\u6570").setDesc("\u663E\u793A\u6700\u8FD1\u591A\u5C11\u5468\u7684\u70ED\u529B\u56FE\uFF0810-104\uFF09").addText((text) => text.setPlaceholder("54").setValue(this.plugin.settings.heatWeeks.toString()).onChange(async (value) => {
      const num = parseInt(value);
      if (!isNaN(num) && num >= 10 && num <= 104) {
        this.plugin.settings.heatWeeks = num;
        await this.plugin.saveSettings();
      }
    }));
    new import_obsidian3.Setting(containerEl).setName("\u6587\u4EF6\u5939\u6392\u884C\u6570\u91CF").setDesc("\u663E\u793A\u524DN\u4E2A\u6587\u4EF6\u5939\uFF081-50\uFF09").addText((text) => text.setPlaceholder("5").setValue(this.plugin.settings.folderTopN.toString()).onChange(async (value) => {
      const num = parseInt(value);
      if (!isNaN(num) && num >= 1 && num <= 50) {
        this.plugin.settings.folderTopN = num;
        await this.plugin.saveSettings();
      }
    }));
    new import_obsidian3.Setting(containerEl).setName("\u5F85\u529E\u6807\u7B7E").setDesc("\u542B\u8FD9\u4E9B\u6807\u7B7E\u7684\u4EFB\u52A1\u6807\u8BB0\u4E3A\u91CD\u8981/\u7D27\u6025\uFF08\u7528\u9017\u53F7\u5206\u9694\uFF09").addText((text) => text.setPlaceholder("#urgent, #important, #doing").setValue(this.plugin.settings.taskTags.join(", ")).onChange(async (value) => {
      this.plugin.settings.taskTags = value.split(",").map((s) => s.trim()).filter((s) => s);
      await this.plugin.saveSettings();
    }));
    new import_obsidian3.Setting(containerEl).setName("\u6708\u5EA6\u56FE\u8868\u6708\u6570").setDesc("\u663E\u793A\u6700\u8FD1\u51E0\u4E2A\u6708\u7684\u56FE\u8868\uFF081-24\uFF09").addText((text) => text.setPlaceholder("12").setValue(this.plugin.settings.monthCount.toString()).onChange(async (value) => {
      const num = parseInt(value);
      if (!isNaN(num) && num >= 1 && num <= 24) {
        this.plugin.settings.monthCount = num;
        await this.plugin.saveSettings();
      }
    }));
    new import_obsidian3.Setting(containerEl).setName("7\u5929\u56FE\u8868\u5929\u6570").setDesc("\u663E\u793A\u6700\u8FD1\u51E0\u5929\u7684\u56FE\u8868\uFF083-30\uFF09").addText((text) => text.setPlaceholder("7").setValue(this.plugin.settings.dayCount.toString()).onChange(async (value) => {
      const num = parseInt(value);
      if (!isNaN(num) && num >= 3 && num <= 30) {
        this.plugin.settings.dayCount = num;
        await this.plugin.saveSettings();
      }
    }));
    new import_obsidian3.Setting(containerEl).setName("\u5F85\u529E\u770B\u677F\u9ED8\u8BA4\u5C55\u5F00\u6570").setDesc("\u9ED8\u8BA4\u5C55\u5F00\u524DN\u4E2A\u6587\u4EF6\u7684\u4EFB\u52A1\uFF081-10\uFF09").addText((text) => text.setPlaceholder("3").setValue(this.plugin.settings.maxOpen.toString()).onChange(async (value) => {
      const num = parseInt(value);
      if (!isNaN(num) && num >= 1 && num <= 10) {
        this.plugin.settings.maxOpen = num;
        await this.plugin.saveSettings();
      }
    }));
    new import_obsidian3.Setting(containerEl).setName("\u4F30\u8BA1\u9608\u503C").setDesc("\u5B57\u6570\u8D85\u8FC7\u6B64\u503C\u89C6\u4E3A\u957F\u6587\uFF08\u7528\u4E8E\u7EDF\u8BA1\uFF09").addText((text) => text.setPlaceholder("200").setValue(this.plugin.settings.estThreshold.toString()).onChange(async (value) => {
      const num = parseInt(value);
      if (!isNaN(num) && num >= 0) {
        this.plugin.settings.estThreshold = num;
        await this.plugin.saveSettings();
      }
    }));
    new import_obsidian3.Setting(containerEl).setName("\u4F30\u8BA1\u7CFB\u6570").setDesc("\u6BCF\u5206\u949F\u9605\u8BFB\u5B57\u6570\uFF08\u7528\u4E8E\u9605\u8BFB\u65F6\u95F4\u4F30\u7B97\uFF09").addText((text) => text.setPlaceholder("4").setValue(this.plugin.settings.estCoeff.toString()).onChange(async (value) => {
      const num = parseInt(value);
      if (!isNaN(num) && num >= 1) {
        this.plugin.settings.estCoeff = num;
        await this.plugin.saveSettings();
      }
    }));
  }
};

// main.ts
var VIEW_TYPE = "note-dashboard";
var DashboardView = class extends import_obsidian4.ItemView {
  constructor(leaf, plugin) {
    super(leaf);
    this.cachedData = null;
    this.clickHandler = null;
    this.container = null;
    this.plugin = plugin;
  }
  getViewType() {
    return VIEW_TYPE;
  }
  getDisplayText() {
    return "\u7B14\u8BB0\u770B\u677F";
  }
  getIcon() {
    return "bar-chart-2";
  }
  async onOpen() {
    const container = this.containerEl.children[1];
    container.empty();
    const dashboardEl = container.createDiv({ cls: "note-dashboard" });
    this.container = dashboardEl;
    await this.renderDashboard(dashboardEl);
  }
  async onClose() {
    if (this.container && this.clickHandler) {
      this.container.removeEventListener("click", this.clickHandler);
      this.clickHandler = null;
    }
    this.container = null;
    this.cachedData = null;
  }
  invalidateCache() {
    this.cachedData = null;
    if (this.container) {
      this.renderDashboard(this.container);
    }
  }
  async renderDashboard(container) {
    const settings = this.plugin.settings;
    const scheme = COLOR_SCHEMES[settings.colorScheme] || COLOR_SCHEMES.indigo;
    if (!this.cachedData) {
      this.cachedData = await collectData(
        this.app.vault,
        settings.exclude,
        settings.planPath,
        settings.taskTags
      );
    }
    const data = this.cachedData;
    let html = "";
    for (const section of settings.sectionOrder) {
      switch (section) {
        case "heat":
          html += '<div data-section="heat"><div class="nd-title">\u{1F525} \u8FD1\u4E00\u5E74\u8D21\u732E\u70ED\u529B\u56FE</div>';
          html += renderHeatmap(data, scheme, settings.heatWeeks, settings.heatLevels);
          html += "</div>";
          break;
        case "stats":
          html += '<div data-section="stats"><div class="nd-hr"></div><div class="nd-title">\u{1F4C8} \u7EDF\u8BA1\u603B\u89C8</div>';
          html += renderStatsCards(data, scheme);
          html += "</div>";
          break;
        case "chart":
          html += renderChart(data, scheme, settings.monthCount, settings.dayCount);
          break;
        case "rank":
          html += '<div data-section="rank">';
          html += renderRanking(data, scheme, settings.folderTopN);
          html += "</div>";
          break;
        case "plan": {
          const planHtml = renderPlanProgress(data.planContent);
          if (planHtml)
            html += planHtml;
          break;
        }
        case "recent":
          html += renderRecentEdits(data);
          break;
        case "tasks":
          html += '<div data-section="tasks"><div class="nd-hr"></div>';
          html += renderTasksBoard(data, scheme, settings.taskTags, settings.maxOpen, this.app);
          html += "</div>";
          break;
      }
    }
    const scrollTop = container.scrollTop;
    const scrollLeft = container.scrollLeft;
    container.innerHTML = html;
    container.scrollTop = scrollTop;
    container.scrollLeft = scrollLeft;
    this.initChartPanes(container);
    requestAnimationFrame(() => {
      container.querySelectorAll(".nd-anim").forEach((el, i) => {
        el.style.animationDelay = `${i * 0.08}s`;
      });
      setTimeout(() => {
        container.querySelectorAll(".nd-bar-fill").forEach((el) => el.classList.add("nd-in"));
      }, 300);
      const heatScroll = container.querySelector(".nd-heat-scroll");
      if (heatScroll) {
        heatScroll.scrollLeft = heatScroll.scrollWidth;
      }
    });
    if (this.clickHandler) {
      container.removeEventListener("click", this.clickHandler);
    }
    this.clickHandler = (e) => this.handleClick(e, container);
    container.addEventListener("click", this.clickHandler);
  }
  initChartPanes(container) {
    const dayPane = container.querySelector('.nd-chart-pane[data-chart-type="day"]');
    if (dayPane && !dayPane.dataset.loaded) {
      const data = JSON.parse(dayPane.dataset.chartData || "[]");
      const bar0 = dayPane.dataset.bar0 || "";
      const bar1 = dayPane.dataset.bar1 || "";
      const primary = dayPane.dataset.primary || "";
      renderChartPane(dayPane, data, bar0, bar1, primary);
      dayPane.dataset.loaded = "1";
    }
  }
  handleClick(e, container) {
    var _a;
    const target = e.target;
    const link = target.closest("[data-nd-link]");
    if (link) {
      const path = link.getAttribute("data-nd-link");
      if (path) {
        this.app.workspace.openLinkText(path, "", false);
      }
    }
    const chartTab = target.closest(".nd-chart-tab");
    if (chartTab) {
      const view = chartTab.getAttribute("data-view");
      const toggle = chartTab.closest(".nd-chart-toggle");
      if (!toggle)
        return;
      const ind = toggle.querySelector("[data-ind]");
      const tabs = toggle.querySelectorAll(".nd-chart-tab");
      const dayPane = container.querySelector('.nd-chart-pane[data-chart-type="day"]');
      const monthPane = container.querySelector('.nd-chart-pane[data-chart-type="month"]');
      if (!dayPane || !monthPane)
        return;
      if (ind) {
        ind.style.left = view === "month" ? "calc(50%)" : "2px";
      }
      tabs.forEach((tab) => {
        tab.style.color = tab === chartTab ? "#fff" : "var(--text-muted)";
      });
      if (view === "month") {
        if (!monthPane.dataset.loaded) {
          const data = JSON.parse(monthPane.dataset.chartData || "[]");
          const bar0 = monthPane.dataset.bar0 || "";
          const bar1 = monthPane.dataset.bar1 || "";
          const primary = monthPane.dataset.primary || "";
          renderChartPane(monthPane, data, bar0, bar1, primary);
          monthPane.dataset.loaded = "1";
        }
        dayPane.style.display = "none";
        monthPane.style.display = "block";
        animChartBars(monthPane);
      } else {
        monthPane.style.display = "none";
        dayPane.style.display = "block";
        animChartBars(dayPane);
      }
      return;
    }
    const rankTab = target.closest(".nd-rank-tab");
    if (rankTab) {
      const targetId = rankTab.getAttribute("data-target");
      const otherId = rankTab.getAttribute("data-other");
      if (targetId) {
        const targetEl = container.querySelector(`#${CSS.escape(targetId)}`);
        if (targetEl)
          targetEl.style.display = "";
      }
      if (otherId) {
        const otherEl = container.querySelector(`#${CSS.escape(otherId)}`);
        if (otherEl)
          otherEl.style.display = "none";
      }
      const tabs = (_a = rankTab.parentElement) == null ? void 0 : _a.querySelectorAll(".nd-rank-tab");
      tabs == null ? void 0 : tabs.forEach((tab) => {
        tab.classList.remove("nd-rank-tab-active");
        tab.style.background = "transparent";
        tab.style.color = "var(--text-muted)";
        tab.style.borderColor = "var(--background-modifier-border)";
      });
      rankTab.classList.add("nd-rank-tab-active");
      rankTab.style.background = "var(--interactive-accent)";
      rankTab.style.color = "#fff";
      rankTab.style.borderColor = "var(--interactive-accent)";
      return;
    }
    const fh = target.closest(".nd-fh");
    if (fh) {
      const tid = fh.getAttribute("data-target");
      const c = tid ? container.querySelector(`#${CSS.escape(tid)}`) : null;
      const a = tid ? container.querySelector(`#${CSS.escape(tid)}-a`) : null;
      if (!c)
        return;
      const isOpen = c.getAttribute("data-open") === "1";
      c.classList.toggle("nd-show", !isOpen);
      if (a)
        a.style.transform = isOpen ? "" : "rotate(90deg)";
      fh.style.borderBottom = isOpen ? "1px solid transparent" : "1px solid var(--background-modifier-border)";
      c.setAttribute("data-open", isOpen ? "0" : "1");
      fh.setAttribute("data-open", isOpen ? "0" : "1");
    }
    const cb = target.closest(".nd-cb");
    if (cb) {
      e.stopPropagation();
      const row = cb.closest(".nd-tr");
      const path = cb.getAttribute("data-path");
      const line = parseInt(cb.getAttribute("data-line") || "0");
      if (!row || !path || !line)
        return;
      cb.textContent = "\u2705";
      cb.style.color = "#22c55e";
      setTimeout(async () => {
        try {
          const file = this.app.vault.getAbstractFileByPath(path);
          if (file) {
            let content = await this.app.vault.read(file);
            content = content.replace(/\r\n/g, "\n");
            const lines = content.split("\n");
            const li = line - 1;
            if (li >= 0 && li < lines.length) {
              lines[li] = lines[li].replace(/^(\s*[-*+]\s*)\[\s\](\s*)/, "$1[x]$2");
              await this.app.vault.modify(file, lines.join("\n"));
            }
          }
          row.remove();
          this.cachedData = null;
        } catch (err) {
          console.error("mark task failed:", err);
          cb.textContent = "\u2B1C";
          cb.style.color = "";
        }
      }, 300);
    }
  }
};
var NoteDashboardPlugin = class extends import_obsidian4.Plugin {
  constructor() {
    super(...arguments);
    this.refreshTimer = null;
  }
  async onload() {
    await this.loadSettings();
    this.registerView(
      VIEW_TYPE,
      (leaf) => new DashboardView(leaf, this)
    );
    this.addRibbonIcon("bar-chart-2", "\u7B14\u8BB0\u770B\u677F", () => {
      this.activateView();
    });
    this.addCommand({
      id: "open-note-dashboard",
      name: "\u6253\u5F00\u7B14\u8BB0\u770B\u677F",
      callback: () => {
        this.activateView();
      }
    });
    this.addCommand({
      id: "refresh-note-dashboard",
      name: "\u5237\u65B0\u7B14\u8BB0\u770B\u677F",
      callback: () => {
        this.refreshDashboard();
      }
    });
    this.addSettingTab(new NoteDashboardSettingTab(this.app, this));
    for (const evt of ["modify", "create", "delete", "rename"]) {
      this.registerEvent(
        this.app.vault.on(evt, () => this.scheduleRefresh())
      );
    }
    this.app.workspace.onLayoutReady(() => {
      if (!this.app.workspace.getLeavesOfType(VIEW_TYPE).length) {
        this.activateView();
      }
    });
  }
  onunload() {
    if (this.refreshTimer !== null) {
      window.clearTimeout(this.refreshTimer);
      this.refreshTimer = null;
    }
  }
  scheduleRefresh() {
    if (this.refreshTimer !== null)
      return;
    this.refreshTimer = window.setTimeout(() => {
      this.refreshTimer = null;
      this.refreshDashboard();
    }, 1e3);
  }
  refreshDashboard() {
    const leaves = this.app.workspace.getLeavesOfType(VIEW_TYPE);
    for (const leaf of leaves) {
      const view = leaf.view;
      if (view instanceof DashboardView) {
        view.invalidateCache();
      }
    }
  }
  async loadSettings() {
    this.settings = Object.assign({}, DEFAULT_SETTINGS, await this.loadData());
  }
  async saveSettings() {
    await this.saveData(this.settings);
    this.refreshDashboard();
  }
  async activateView() {
    const { workspace } = this.app;
    let leaf = null;
    const leaves = workspace.getLeavesOfType(VIEW_TYPE);
    if (leaves.length > 0) {
      leaf = leaves[0];
    } else {
      leaf = workspace.getRightLeaf(false);
      if (leaf) {
        await leaf.setViewState({ type: VIEW_TYPE, active: true });
      }
    }
    if (leaf) {
      workspace.revealLeaf(leaf);
    }
  }
};
